_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 23
                - 55
                - 62
            "4": 3.10.15
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
